export const SEND_BULK_MESSAGE_REQUEST = "SEND_BULK_MESSAGE_REQUEST";
export const SEND_BULK_MESSAGE_SUCCESS = "SEND_BULK_MESSAGE_SUCCESS";
export const SEND_BULK_MESSAGE_FAILURE = "SEND_BULK_MESSAGE_FAILURE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";
